---
name: POE-Component-WWW-PAUSE-RecentUpoads-Tail
version: 0.04
author:
  - 'Zoffix Znet <zoffix@cpan.org>'
abstract: "tail recent uploads\nto PAUSE."
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 1.04
  POE: 0.9999
  POE::Component::WWW::PAUSE::RecentUploads: 0.02
  Storable: 2.15
build_requires:
  Test::More: 0
provides:
  POE::Component::WWW::PAUSE::RecentUpoads::Tail:
    file: lib/POE/Component/WWW/PAUSE/RecentUpoads/Tail.pm
    version: 0.04
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
